# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{socky-server}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bernard Potocki"]
  s.date = %q{2011-05-12}
  s.default_executable = %q{socky}
  s.description = %q{Socky is a WebSocket server and client for Ruby}
  s.email = %q{bernard.potocki@imanel.org}
  s.executables = ["socky"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "CHANGELOG.textile",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/socky",
    "lib/em-websocket_hacks.rb",
    "lib/socky.rb",
    "lib/socky/connection.rb",
    "lib/socky/connection/authentication.rb",
    "lib/socky/connection/finders.rb",
    "lib/socky/message.rb",
    "lib/socky/misc.rb",
    "lib/socky/net_request.rb",
    "lib/socky/options.rb",
    "lib/socky/options/config.rb",
    "lib/socky/options/parser.rb",
    "lib/socky/runner.rb",
    "socky-server.gemspec",
    "spec/em-websocket_spec.rb",
    "spec/files/default.yml",
    "spec/files/invalid.yml",
    "spec/socky/connection/authentication_spec.rb",
    "spec/socky/connection/finders_spec.rb",
    "spec/socky/connection_spec.rb",
    "spec/socky/message_spec.rb",
    "spec/socky/misc_spec.rb",
    "spec/socky/net_request_spec.rb",
    "spec/socky/options/config_spec.rb",
    "spec/socky/options/parser_spec.rb",
    "spec/socky/options_spec.rb",
    "spec/socky/runner_spec.rb",
    "spec/socky_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/stallion.rb"
  ]
  s.homepage = %q{http://imanel.org/projects/socky}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.1}
  s.summary = %q{Socky is a WebSocket server and client for Ruby}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<em-websocket>, ["~> 0.3.0"])
      s.add_runtime_dependency(%q<em-http-request>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
      s.add_development_dependency(%q<rack>, [">= 0"])
      s.add_development_dependency(%q<mongrel>, [">= 0"])
    else
      s.add_dependency(%q<em-websocket>, ["~> 0.3.0"])
      s.add_dependency(%q<em-http-request>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
      s.add_dependency(%q<rack>, [">= 0"])
      s.add_dependency(%q<mongrel>, [">= 0"])
    end
  else
    s.add_dependency(%q<em-websocket>, ["~> 0.3.0"])
    s.add_dependency(%q<em-http-request>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
    s.add_dependency(%q<rack>, [">= 0"])
    s.add_dependency(%q<mongrel>, [">= 0"])
  end
end

